# Generated by Django 5.2.12 on 2026-03-22 00:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_user_roles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='full_name',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(message='ФИО должно содержать только русские буквы', regex='^[А-Яа-яЁё\\s]+$')], verbose_name='ФИО'),
        ),
    ]
