# Generated by Django 5.2.12 on 2026-03-22 07:04

import django.core.validators
import django.db.models.deletion
import player.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioRecording',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('audio_file', models.FileField(upload_to='recordings/', verbose_name='Аудиозапись')),
                ('duration', models.PositiveIntegerField(default=0, verbose_name='Длительность (сек)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата записи')),
                ('added_to_playlist', models.BooleanField(default=False, verbose_name='Добавлен в плейлист')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audio_recordings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Аудиозапись',
                'verbose_name_plural': 'Аудиозаписи',
            },
        ),
        migrations.CreateModel(
            name='MediaFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('file', models.FileField(upload_to=player.models.user_media_path, verbose_name='Файл')),
                ('media_type', models.CharField(choices=[('audio', 'Аудио'), ('video', 'Видео')], max_length=10, verbose_name='Тип медиа')),
                ('duration', models.PositiveIntegerField(default=0, verbose_name='Длительность (сек)')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Удален')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_files', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Медиафайл',
                'verbose_name_plural': 'Медиафайлы',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Сообщение')),
                ('status', models.CharField(choices=[('new', 'Новый'), ('in_progress', 'В работе'), ('completed', 'Завершено')], default='new', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('is_active', models.BooleanField(default=False, verbose_name='Активен')),
                ('loop', models.BooleanField(default=False, verbose_name='Зацикливание')),
                ('shuffle', models.BooleanField(default=False, verbose_name='Перемешивание')),
                ('is_playing', models.BooleanField(default=False, verbose_name='Воспроизводится')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlists', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Плейлист',
                'verbose_name_plural': 'Плейлисты',
            },
        ),
        migrations.CreateModel(
            name='Broadcast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False, verbose_name='Активна')),
                ('volume', models.PositiveIntegerField(default=70, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)], verbose_name='Громкость')),
                ('mic_enabled', models.BooleanField(default=False, verbose_name='Микрофон включен')),
                ('cam_enabled', models.BooleanField(default=False, verbose_name='Камера включена')),
                ('has_video', models.BooleanField(default=False, verbose_name='Есть видео')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Начало трансляции')),
                ('ended_at', models.DateTimeField(blank=True, null=True, verbose_name='Окончание трансляции')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='broadcasts', to=settings.AUTH_USER_MODEL)),
                ('playlist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='broadcasts', to='player.playlist')),
            ],
            options={
                'verbose_name': 'Трансляция',
                'verbose_name_plural': 'Трансляции',
            },
        ),
        migrations.CreateModel(
            name='PlaylistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('media_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlist_items', to='player.mediafile')),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='player.playlist')),
            ],
            options={
                'verbose_name': 'Элемент плейлиста',
                'verbose_name_plural': 'Элементы плейлиста',
                'ordering': ['order'],
            },
        ),
    ]
